### ISSUE TITLE
java.lang.ClassNotFoundException: com.lightstreamer.log.Logger

### ISSUE THREAD

**Issue by leiguorui** [Lightstreamer/Lightstreamer-example-Quickstart-client-java#3]
I get a error when I run the demo.

Connected to the target VM, address: '127.0.0.1:49450', transport: 'socket'
Exception in thread "main" java.lang.NoClassDefFoundError: com/lightstreamer/log/Logger
	at cn.injava.forex.stream.Stocklist.start(Stocklist.java:62)
	at cn.injava.forex.stream.Stocklist.main(Stocklist.java:53)
Caused by: java.lang.ClassNotFoundException: com.lightstreamer.log.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by acarioni** [comment]
The simpler way to run the demo is by building the project with Maven. The project is shipped with the file _pom.xml_ listing all the dependencies you need, including the class _com.lightstreamer.log.Logger_, which is the cause of the error.
If you want to set up your environment by hand, you have to download the jars _ls-javase-client.jar_ and _ls-log-adapter.jar_ from our [Maven repository](https://lightstreamer.com/repo/maven/com/lightstreamer/), and add them to the classpath of the application.
